name: Spring Boot Docker CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spring-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Set Gradle permissions
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test --no-daemon

#      - name: Build Spring Boot JAR
#        run: ./gradlew clean build --no-daemon

      # --- DockerHub Login ---
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # --- Docker Build & Push ---
      - name: Build & Push Spring Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/community-be:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/community-be:latest

#  spring-cd:
#    needs: spring-ci
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Prepare SSH key
#        run: |
#          mkdir -p ~/.ssh
#          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
#
#      - name: Deploy to EC2 via Docker Compose
#        run: |
#          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER}}@${{ secrets.SERVER_HOST }} << 'EOF'
#              cd /home/${{ secrets.SERVER_USER }}/be
#              docker compose pull
#              docker compose up -d
#          EOF