name: Spring Boot Docker CI-CD Private

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spring-private-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Set Gradle permissions
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test --no-daemon

      - name: Build Spring Boot JAR
        run: ./gradlew clean build --no-daemon

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login \
            --username AWS \
            --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build & Push Express Image
        run: |
          IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/community-be:latest
          docker build -t $IMAGE .
          docker push $IMAGE

  spring-private-cd:
    needs: spring-private-ci
    runs-on: ubuntu-latest

    steps:
      # AWS 인증
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to EC2 via SSM
        run: |
          ECR_PASSWORD=$(aws ecr get-login-password --region ap-northeast-2)
          
          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --parameters commands="[
              \"echo '$ECR_PASSWORD' | sudo docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com\",
              \"cd /home/ubuntu/fe\",
              \"sudo docker compose pull\",
              \"sudo docker compose up -d\"
            ]" \
            --comment "Deploy from Github Actions" \
            --output text \
            --query "Command.CommandId")
          
          echo "Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "${{ secrets.EC2_INSTANCE_ID }}"
          
          STATUS=$(aws ssm get-command-invocation \
          --command-id "$COMMAND_ID" \
          --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
          --query "Status" \
          --output text)
          
          if [ "$STATUS" != "Success" ]; then
            exit 1
          fi